import { BusinessCaseActivity } from "src/modules/business-case/entities/business-case-activity.entity";


export const REPOSITORIES = {
  ACCIDENTCASEDOCUMENTS_REPOSITORY:'ACCIDENTCASEDOCUMENTS_REPOSITORY',
  USERREGION_REPOSITORY: 'USERREGION_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  SUPER_USER_REPOSITORY: 'SUPER_USER_REPOSITORY',
  LOGIN_TOKEN_REPOSITORY: 'LOGIN_TOKEN_REPOSITORY',
  FORGOT_PASSWORD_REPOSITORY: 'FORGOT_PASSWORD_REPOSITORY',
  USER_LOCATION_REPOSITORY: 'USER_LOCATION_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  ROLE_PERMISSION_REPOSITORY: 'ROLE_PERMISSION_REPOSITORY',
  PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
  INSURANCECOMPANY_REPOSITORY: 'INSURANCECOMPANY_REPOSITORY',
  TOWSERVICE_REPOSITORY:  'TOWSERVICE_REPOSITORY',
  REGION_REPOSITORY:  'REGION_REPOSITORY',
  WORKSHOP_REPOSITORY: 'WORKSHOP_REPOSITORY',
  COMPANYROLE_REPOSITORY: 'COMPANYROLE_REPOSITORY',
  USERPERMISSION_REPOSITORY: 'USERPERMISSION_REPOSITORY',
  INSURANCEDOCUMENTS_REPOSITORY: 'INSURANCEDOCUMENTS_REPOSITORY',
  INSURANCECOMPANYUSER_REPOSITORY: 'INSURANCECOMPANYUSER_REPOSITORY', 
  PARTICIPANT_REPOSITORY: 'PARTICIPANT_REPOSITORY',
  ACCIDENTSCENARIO_REPOSITORY: 'ACCIDENTSCENARIO_REPOSITORY',
  ACCIDENTCASE_REPOSITORY: 'ACCIDENTCASE_REPOSITORY',
  DRAWDAMAGE_REPOSITORY: 'DRAWDAMAGE_REPOSITORY',
  LEASINGINSURANCECOMPANY_REPOSITORY: 'LEASINGINUSRANCECOMPANY_REPOSITORY',
  LIABILITYINSURANCECOMPANY_REPOSITORY: 'LIABILITYINUSRANCECOMPANY_REPOSITORY',
  AKAINSURANCECOMPANY_REPOSITORY: 'AKAINUSRANCECOMPANY_REPOSITORY',
  DAMAGEINSURANCECOMPANY_REPOSITORY: 'DAMAGEINUSRANCECOMPANY_REPOSITORY',
  BUSINESSCASE_REPOSITORY: 'BUSINESSCASE_REPOSITORY',
  BUSINESSCASEACTIVITY_REPOSITORY: 'BUSINESSCASEACTIVITY_REPOSITORY',
  BUSINESSCASEDOCUMENTS_REPOSITORY: 'BUSINESSCASEDOCUMENTS_REPOSITORY',
  BUSINESSCASETOWSERVICE_REPOSITORY: 'BUSINESSCASETOWSERVICE_REPOSITORY',
  RESOURCESHARING_REPOSITORY: 'RESOURCESHARING_REPOSITORY',


};