import { 
    NAV_ITEM_TYPE_TITLE, 
    NAV_ITEM_TYPE_ITEM 
} from '@/constants/navigation.constant'

const navigationConfig = [

			{
				key: "dashboard",
				path: `/dashboard`,
				title: "Dashboard",
				translateKey: "nav.dashboard",
				icon: "dashboard",
				type: NAV_ITEM_TYPE_ITEM,
				authority: [],
				all:true,
				subMenu: [],
			},
			{
				key: "role",
				path: `/role`,
				title: "Role",
				translateKey: "nav.role",
				icon: "role",
				authority: ["can_view_role"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "insurance-company",
				path: `/insurance-company`,
				title: "Insurance Company",
				translateKey: "nav.insurance-company",
				icon: "insuranceCompany",
				authority: ["can_view_insurance_company"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "leasing-company",
				path: `/leasing-company`,
				title: "Leasing Company",
				translateKey: "nav.leasing-company",
				icon: "leasingCompany",
				authority: ["can_view_leasing_insurance_company"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "workshop",
				path: `/workshop`,
				title: "Workshop",
				translateKey: "nav.workshop",
				icon: "workshop",
				authority: ["can_view_workshop"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "towService",
				path: `/tow-service`,
				title: "Tow Service",
				translateKey: "nav.tow-service",
				authority: ["can_view_tow_service"],
				icon: "towService",
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "region",
				path: `/region`,
				title: "Region",
				translateKey: "nav.region",
				authority: ["can_view_region"],
				icon: "region",
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "business-agent",
				path: `/business-agent`,
				title: "Business Agent ",
				translateKey: "nav.business-agent",
				icon: "businessAgent",
				authority: ["can_view_business_agent"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "sale-agent",
				path: `/sale-agent`,
				title: "Sale Agent",
				translateKey: "nav.sale-agent",
				authority: ["can_view_sale_agents"],
				icon: "saleAgent",
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			}, 
			{
				key: "submit-case",
				path: `/submit-case`,
				title: "Submit Case",
				translateKey: "nav.submit-case",
				authority: ["can_view_submit_case"],
				icon: "submitCase",
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			}, 

			{
				key: "cases-list",
				path: `/cases-list`,
				title: "Cases List",
				translateKey: "nav.cases-list",
				icon: "casesList",
				authority: ["can_view_cases_list"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "business-case",
				path: `/business-case`,
				title: "Business Case",
				translateKey: "nav.business-case",
				icon: "businessCase",
				authority: ["can_view_business_case"],
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},

			{
				key: "account-settings",
				path: `/account-settings`,
				title: "Account Settings",
				translateKey: "nav.accountsetting",
				icon: "accountSettings",
				authority: [],
				all:true,
				type: NAV_ITEM_TYPE_ITEM,
				subMenu: [],
			},
			{
				key: "logout",
				title: "Sign Out",
				translateKey: "nav.logout",
				icon: "logout",
				type: NAV_ITEM_TYPE_ITEM,
				authority: [],
				subMenu: [],
				all:true,
				admin:true,
				authority: [],
				onClick: "signOut",
			}
		];
			


export default navigationConfig